export { default as Button } from '../components/Button'
export { default as Categories } from '../components/Categories'
export { default as Header } from '../components/Header'
export { default as SortPopup } from '../components/SortPopup'
export { default as Home } from '../components/Home'
export { default as Cart } from '../components/Cart'
export { default as PizzasLoader } from '../components/ContentLoader'
export { default as CartItem } from '../components/CartItem'
